/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
StereoSourceSeparationAudioProcessorEditor::StereoSourceSeparationAudioProcessorEditor (StereoSourceSeparationAudioProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter)
{
    width_ = 600;
    height_ = 300;
    dirAngle = M_PI/2;
    widAngle = M_PI/8;
    radius = width_/2-5;
    arrowLine = Line<float>(width_/2+100, height_+100, 100+width_/2+radius*cos(dirAngle), 100+height_-radius*sin(dirAngle));
    paintColour = Colours::grey;
    
    addAndMakeVisible(widthSlider = new Slider());
    widthSlider->setTextBoxStyle(Slider::NoTextBox, true, 220, 30);
    widthSlider->setColour(Slider::thumbColourId, Colours::wheat);
    widthSlider->setColour(Slider::trackColourId, Colours::wheat);
    widthSlider->setRange(0, 100);
    widthSlider->setValue(12.5);
    widthSlider->addListener(this);
    
    addAndMakeVisible (soloToggle = new ToggleButton ("Solo"));
    soloToggle->setColour(TextButton::buttonColourId, Colours::lightblue);
    soloToggle->setColour(ToggleButton::textColourId, Colours::lightblue);
    soloToggle->addListener (this);
    
    addAndMakeVisible (muteToggle = new ToggleButton ("Mute"));
    muteToggle->setColour(TextButton::buttonColourId, Colours::pink);
    muteToggle->setColour(ToggleButton::textColourId, Colours::pink);
    muteToggle->addListener (this);
    
    addAndMakeVisible (bypassToggle = new ToggleButton ("Bypass"));
    bypassToggle->setColour(TextButton::buttonColourId, Colours::lightgrey);
    bypassToggle->setColour(ToggleButton::textColourId, Colours::lightgrey);
    bypassToggle->setToggleState(true, juce::sendNotification);
    bypassToggle->addListener (this);
    
    addAndMakeVisible (dirLabel = new Label (String::empty,"Direction : "));
    dirLabel->setFont (Font (20.00f, Font::bold));
    dirLabel->setJustificationType (Justification::centred);
    dirLabel->setEditable (false, false, false);
    dirLabel->setColour (Label::textColourId, Colours::wheat);
    dirLabel->setColour (TextEditor::textColourId, Colours::wheat);
    dirLabel->setColour (TextEditor::backgroundColourId, Colour (0x00000000));
    
    addAndMakeVisible (widLabel = new Label (String::empty,"Width : +/-"));
    widLabel->setFont (Font (20.00f, Font::bold));
    widLabel->setJustificationType (Justification::centred);
    widLabel->setEditable (false, false, false);
    widLabel->setColour (Label::textColourId, Colours::wheat);
    widLabel->setColour (TextEditor::textColourId, Colours::wheat);
    widLabel->setColour (TextEditor::backgroundColourId, Colour (0x00000000));
    
    addAndMakeVisible (dirVal = new Label (String::empty, "0"));
    dirVal->setFont (Font (20.00f, Font::bold));
    dirVal->setJustificationType (Justification::centred);
    dirVal->setEditable (false, false, false);
    dirVal->setColour (Label::textColourId, Colours::wheat);
    dirVal->setColour (TextEditor::textColourId, Colours::wheat);
    dirVal->setColour (TextEditor::backgroundColourId, Colour (0x00000000));
    
    addAndMakeVisible (widVal = new Label (String::empty, "22.5"));
    widVal->setFont (Font (20.00f, Font::bold));
    widVal->setJustificationType (Justification::centred);
    widVal->setEditable (false, false, false);
    widVal->setColour (Label::textColourId, Colours::wheat);
    widVal->setColour (TextEditor::textColourId, Colours::wheat);
    widVal->setColour (TextEditor::backgroundColourId, Colour (0x00000000));
    
    addAndMakeVisible (sideVal = new Label (String::empty, "M"));
    sideVal->setFont (Font (20.00f, Font::bold));
    sideVal->setJustificationType (Justification::centred);
    sideVal->setEditable (false, false, false);
    sideVal->setColour (Label::textColourId, Colours::wheat);
    sideVal->setColour (TextEditor::textColourId, Colours::wheat);
    sideVal->setColour (TextEditor::backgroundColourId, Colour (0x00000000));
    
    setSize (900, 600);
}

StereoSourceSeparationAudioProcessorEditor::~StereoSourceSeparationAudioProcessorEditor()
{
    widthSlider = nullptr;
    soloToggle = nullptr;
    muteToggle = nullptr;
    bypassToggle = nullptr;
    dirLabel = nullptr;
    widLabel = nullptr;
    dirVal = nullptr;
    widVal = nullptr;
    sideVal = nullptr;
}

//==============================================================================
void StereoSourceSeparationAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll(Colours::darkgrey);
    g.setColour (paintColour);
    g.fillPath (internalPath);
    g.strokePath (internalPath, PathStrokeType (1.200f));
    g.setColour(Colour (0xff3b3b3b));
    g.fillPath (arrowPath);
    g.strokePath (arrowPath, PathStrokeType (1.200f));
    g.setColour (Colours::wheat);
    g.drawEllipse(100+5, 100+5, width_-10, 2*height_-10, 8);
    g.setColour(Colours::darkgrey);
    g.fillRect(0, 100+height_, getWidth(), getHeight()-height_-100);
}

void StereoSourceSeparationAudioProcessorEditor::resized()
{
    internalPath.clear();
    internalPath.startNewSubPath (width_/2+100, height_+100);
    internalPath.addCentredArc(width_/2+100, height_+100, radius, radius, 0, (M_PI/2-dirAngle-widAngle+2*M_PI), (M_PI/2-dirAngle+widAngle+M_PI*2), false);
    internalPath.closeSubPath();
    arrowPath.clear();
    arrowPath.startNewSubPath (width_/2+100, height_+100);
    arrowPath.addArrow(arrowLine, 5, 20, 20);
    arrowPath.closeSubPath();
    
    widthSlider->setBounds( 200, 450, 400, 40);
    soloToggle->setBounds(750, 200, 100, 50);
    muteToggle->setBounds(750, 300, 100, 50);
    bypassToggle->setBounds(750, 400, 100, 50);
    dirLabel->setBounds(200, 50, 80, 25);
    widLabel->setBounds(500, 50, 100, 25);
    dirVal->setBounds(320, 50, 60, 25);
    widVal->setBounds(600, 50, 60, 25);
    sideVal->setBounds(280, 50, 40, 25);
}


void StereoSourceSeparationAudioProcessorEditor::mouseDrag (const juce::MouseEvent &e)
{
    dirAngle = atanf((height_+100-e.getPosition().y)*1.0/(e.getPosition().x-width_/2-100));
    if (dirAngle<0)
        dirAngle += M_PI;
    
    int dirAngle_toPass = (int)(M_PI-dirAngle)/M_PI*100;
    
    if (dirAngle > M_PI/2)
        sideVal->setText("L", juce::sendNotification);
    else if (dirAngle == M_PI/2)
        sideVal->setText("M", juce::sendNotification);
    else
        sideVal->setText("R", juce::sendNotification);
    dirVal->setText(String(fabs((dirAngle-M_PI/2)*180/M_PI)), juce::sendNotification);
    arrowLine.setEnd(100+width_/2+radius*cos(dirAngle), 100+height_-radius*sin(dirAngle));
    resized();
    repaint();
}

void StereoSourceSeparationAudioProcessorEditor::sliderValueChanged (Slider* slider)
{
    widAngle = slider->getValue()/100*M_PI;
    widVal->setText(String(widAngle*180/M_PI), juce::sendNotification);
    resized();
    repaint();
}

void StereoSourceSeparationAudioProcessorEditor::buttonClicked (Button* buttonThatWasClicked)
{
    if (buttonThatWasClicked == soloToggle && soloToggle->getToggleState())
    {
        muteToggle->setToggleState(false, juce::sendNotification);
        bypassToggle->setToggleState(false, juce::sendNotification);
        paintColour = Colours::lightblue;
    }
    else if (buttonThatWasClicked == muteToggle && muteToggle->getToggleState())
    {
        soloToggle->setToggleState(false, juce::sendNotification);
        bypassToggle->setToggleState(false, juce::sendNotification);
        paintColour = Colour (0xfff08080);
    }
    else if (buttonThatWasClicked == bypassToggle && bypassToggle->getToggleState())
    {
        soloToggle->setToggleState(false, juce::sendNotification);
        muteToggle->setToggleState(false, juce::sendNotification);
        paintColour = Colours::grey;
    }
    repaint();
}