/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "DirectionComponent.h"

//==============================================================================
/**
*/
class StereoSourceSeparationAudioProcessorEditor  : public AudioProcessorEditor,
                                                    public ButtonListener,
                                                    public SliderListener,
                                                    public Timer
{
public:
    StereoSourceSeparationAudioProcessorEditor (StereoSourceSeparationAudioProcessor* ownerFilter);
    ~StereoSourceSeparationAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics&) override;
    void resized() override;
    void timerCallback() override;
    void sliderValueChanged (Slider*) override;
    void buttonClicked (Button* buttonThatWasClicked);

private:
    ScopedPointer<DirectionComponent> directionComponent;

};


#endif  // PLUGINEDITOR_H_INCLUDED
