/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
StereoSourceSeparationAudioProcessorEditor::StereoSourceSeparationAudioProcessorEditor (StereoSourceSeparationAudioProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter),
      directionComponent()
{
    addAndMakeVisible(directionComponent = new DirectionComponent());
    setSize (900, 600);
}

StereoSourceSeparationAudioProcessorEditor::~StereoSourceSeparationAudioProcessorEditor()
{
    directionComponent = nullptr;
}

//==============================================================================
void StereoSourceSeparationAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::darkgrey);
}

void StereoSourceSeparationAudioProcessorEditor::resized()
{
    directionComponent->setBounds(0, 0, getWidth(), (int)(getHeight()*4/5));
}

void StereoSourceSeparationAudioProcessorEditor::timerCallback()
{
    
}

void StereoSourceSeparationAudioProcessorEditor::sliderValueChanged (Slider* slider)
{

}

void StereoSourceSeparationAudioProcessorEditor::buttonClicked (Button* buttonThatWasClicked)
{

}